import { Dhis2FormElement } from "../interface/dhis2FormElement.interface";

export enum Action {
    showError = "SHOWERROR",
    hideField = "HIDEFIELD",
}

export const DATA_ELEMENTS = {
    departureCountry: "cZpW431xdsq",
    passport:"v5KB4meGBFe",
    otherPassport:"e2Erb6wn0rc",
    vomiting: "wtCmGyawb4E",
    fever: "EWZcuvPOrJF",
    lethargy: "l2CCqtRVrOg",
    bleeding: "JRQbs8iwbj0",
    hicuups: "xJFi2DwJ6sY",
    skinRash: "SeKu9WMNh16",
    swallowingDifficult: "C8J5HoUNIuG",
    stomachPain: "ySDjXlmGIye",
    headache: "iUEwXfg9CgD",
    diarrhea: "IrFWIj5ks2p",
    throat: "T0ehgpsDrui",
    musclePain: "HahhmzRvwu8",
    lossAppetie: "FLldQkmyokg",
    breathingDifficult: "Nbs08NkwUVK",
    temperature: "BH5SRLl5PfH",
    anySigns: "JGnHr6WI3AY",
    contactPhoneInSouthSudan: "Cs1wQfbUHSV",
    firstCountryVisited: "KhAl7eY8tdX",
    secondCountryVisited: "AOg1wewJiRE",
    thirdCountryVisited: "Xak52XWejN2",
};

export const Dhis2Elements = [
    {
        condition: `${DATA_ELEMENTS.departureCountry} == 'SS'`,
        action: Action.showError,
        message: "Country of Departure can't be South Sudan",
        dataElement: `${DATA_ELEMENTS.departureCountry}"`,
        respondedDataElement: `${DATA_ELEMENTS.departureCountry}`,
        displayName: "Country",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.vomiting}`,
        respondedDataElement: `${DATA_ELEMENTS.vomiting}`,
        displayName: "Sign/Symptoms Nausea/vomiting pain",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.fever}`,
        respondedDataElement: `${DATA_ELEMENTS.fever}`,
        displayName: "Sign/Symptoms Fever",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.lethargy}`,
        respondedDataElement: `${DATA_ELEMENTS.lethargy}`,
        displayName: "Lethargy (general weakness)",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.bleeding}`,
        respondedDataElement: `${DATA_ELEMENTS.bleeding}`,
        displayName: "Unexplained bleeding",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.hicuups}`,
        respondedDataElement: `${DATA_ELEMENTS.hicuups}`,
        displayName: "Hiccups",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.skinRash}`,
        respondedDataElement: `${DATA_ELEMENTS.skinRash}`,
        displayName: "Sign/Symptoms skin rash",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.swallowingDifficult}`,
        respondedDataElement: `${DATA_ELEMENTS.swallowingDifficult}`,
        displayName: "Difficulty in swallowing",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.stomachPain}`,
        respondedDataElement: `${DATA_ELEMENTS.stomachPain}`,
        displayName: "Stomach Pain",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.headache}`,
        respondedDataElement: `${DATA_ELEMENTS.headache}`,
        displayName: "Sign/Symptoms headache",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.diarrhea}`,
        respondedDataElement: `${DATA_ELEMENTS.diarrhea}`,
        displayName: "Sign/Symptoms diarrhea",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.throat}`,
        respondedDataElement: `${DATA_ELEMENTS.throat}`,
        displayName: "Sign/Symptoms sore throat",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.musclePain}`,
        respondedDataElement: `${DATA_ELEMENTS.musclePain}`,
        displayName: "Sign/Symptoms muscle pain",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.lossAppetie}`,
        respondedDataElement: `${DATA_ELEMENTS.lossAppetie}`,
        displayName: "Loss of appetite",
    },
    {
        condition: `${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.breathingDifficult}`,
        respondedDataElement: `${DATA_ELEMENTS.breathingDifficult}`,
        displayName: "Breathing difficulties",
    },
    {
        condition: `${DATA_ELEMENTS.fever} != true || ${DATA_ELEMENTS.anySigns} != 'Yes'`,
        action: Action.hideField,
        message: "",
        dataElement: `${DATA_ELEMENTS.temperature}`,
        respondedDataElement: `${DATA_ELEMENTS.temperature}`,
        displayName: "Temperature",
    },
    {
        condition: `hasValue(${DATA_ELEMENTS.temperature}) && (${DATA_ELEMENTS.temperature} < 30 || ${DATA_ELEMENTS.temperature} > 45)`,
        action: Action.showError,
        message: "Provide normal human temperature",
        dataElement: `${DATA_ELEMENTS.temperature}`,
        respondedDataElement: `${DATA_ELEMENTS.anySigns}`,
        displayName: "Sign/Symptoms Present",
    },
    {
        condition: `hasValue(${DATA_ELEMENTS.contactPhoneInSouthSudan}) && length(${DATA_ELEMENTS.contactPhoneInSouthSudan}) != 12`,
        action: Action.showError,
        message: "Indicate the format for the south sudan phone format",
        dataElement: `${DATA_ELEMENTS.contactPhoneInSouthSudan}`,
        respondedDataElement: `${DATA_ELEMENTS.contactPhoneInSouthSudan}`,
        displayName: "Contact phone number while in South Sudan",
    },
    {
        condition: `hasValue(${DATA_ELEMENTS.thirdCountryVisited}) && (${DATA_ELEMENTS.thirdCountryVisited} == ${DATA_ELEMENTS.secondCountryVisited} || ${DATA_ELEMENTS.thirdCountryVisited} == ${DATA_ELEMENTS.firstCountryVisited} )`,
        action: Action.showError,
        message: "You have already selected this country in 2nd or 1st country you visited",
        dataElement: `${DATA_ELEMENTS.thirdCountryVisited}`,
        respondedDataElement: `${DATA_ELEMENTS.thirdCountryVisited}`,
        displayName: "3rd Country Visited in Last 21 days",
    },
    {
        condition: `hasValue(${DATA_ELEMENTS.secondCountryVisited}) && (${DATA_ELEMENTS.secondCountryVisited} == ${DATA_ELEMENTS.thirdCountryVisited} || ${DATA_ELEMENTS.secondCountryVisited} == ${DATA_ELEMENTS.firstCountryVisited} )`,
        action: Action.showError,
        message: "You have already selected this country in 3rd or 1st country you visited",
        dataElement: `${DATA_ELEMENTS.secondCountryVisited}`,
        respondedDataElement: `${DATA_ELEMENTS.secondCountryVisited}`,
        displayName: "2nd Country Visited in Last 21 days",
    },
    {
        condition: `hasValue(${DATA_ELEMENTS.firstCountryVisited}) && (${DATA_ELEMENTS.firstCountryVisited} == ${DATA_ELEMENTS.secondCountryVisited} || ${DATA_ELEMENTS.firstCountryVisited} == ${DATA_ELEMENTS.thirdCountryVisited} )`,
        action: Action.showError,
        message: "You have already selected this country in 3rd or 1st country you visited",
        dataElement: `${DATA_ELEMENTS.firstCountryVisited}`,
        respondedDataElement: `${DATA_ELEMENTS.firstCountryVisited}`,
        displayName: "1st Country Visited in Last 21 days",
    },
    {
        condition: `length(${DATA_ELEMENTS.passport}) < 4`,
        action: Action.showError,
        message: "Passport number minlength is 4",
        dataElement: `${DATA_ELEMENTS.passport}`,
        respondedDataElement: `${DATA_ELEMENTS.passport}`,
        displayName: "Passport Number",
    },
    {
        condition: `hasValue(${DATA_ELEMENTS.otherPassport})&&length(${DATA_ELEMENTS.otherPassport}) < 4`,
        action: Action.showError,
        message: "Passport number minlength is 4",
        dataElement: `${DATA_ELEMENTS.otherPassport}`,
        respondedDataElement: `${DATA_ELEMENTS.otherPassport}`,
        displayName: "Other Passport Number",
    }
] as Dhis2FormElement[];
