import { Dhis2FormElement } from "../interface/dhis2FormElement.interface";

export enum Action {
    showError = "SHOWERROR",
    hideField = "HIDEFIELD",
}

export const Dhis2Elements = [
    {
        condition: "cZpW431xdsq == 'SS'",
        action: Action.showError,
        message: "Country of Departure can't be South Sudan",
        dataElement: "cZpW431xdsq",
        respondedDataElement: "cZpW431xdsq",
        displayName: "Country",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "wtCmGyawb4E",
        respondedDataElement: "wtCmGyawb4E",
        displayName: "Sign/Symptoms Nausea/vomiting pain",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "EWZcuvPOrJF",
        respondedDataElement: "EWZcuvPOrJF",
        displayName: "Sign/Symptoms Fever",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "l2CCqtRVrOg",
        respondedDataElement: "l2CCqtRVrOg",
        displayName: "Lethargy (general weakness)",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "JRQbs8iwbj0",
        respondedDataElement: "JRQbs8iwbj0",
        displayName: "Unexplained bleeding",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "JxJFi2DwJ6sY",
        respondedDataElement: "xJFi2DwJ6sY",
        displayName: "Hiccups",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "SeKu9WMNh16",
        respondedDataElement: "SeKu9WMNh16",
        displayName: "Sign/Symptoms skin rash",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "C8J5HoUNIuG",
        respondedDataElement: "C8J5HoUNIuG",
        displayName: "Difficulty in swallowing",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "ySDjXlmGIye",
        respondedDataElement: "ySDjXlmGIye",
        displayName: "Stomach Pain",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "iUEwXfg9CgD",
        respondedDataElement: "iUEwXfg9CgD",
        displayName: "Sign/Symptoms headache",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "IrFWIj5ks2p",
        respondedDataElement: "IrFWIj5ks2p",
        displayName: "Sign/Symptoms diarrhea",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "T0ehgpsDrui",
        respondedDataElement: "T0ehgpsDrui",
        displayName: "Sign/Symptoms sore throat",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "HahhmzRvwu8",
        respondedDataElement: "HahhmzRvwu8",
        displayName: "Sign/Symptoms muscle pain",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "FLldQkmyokg",
        respondedDataElement: "FLldQkmyokg",
        displayName: "Loss of appetite",
    },
    {
        condition: "JGnHr6WI3AY != 'Yes'",
        action: Action.hideField,
        message: "",
        dataElement: "Nbs08NkwUVK",
        respondedDataElement: "Nbs08NkwUVK",
        displayName: "Breathing difficulties",
    },
    {
        condition: "EWZcuvPOrJF != 'True'",
        action: Action.hideField,
        message: "",
        dataElement: "BH5SRLl5PfH",
        respondedDataElement: "BH5SRLl5PfH",
        displayName: "Temperature",
    },
    {
        condition: "hasValue(BH5SRLl5PfH) && (BH5SRLl5PfH < 30 || BH5SRLl5PfH > 45)",
        action: Action.showError,
        message: "Provide normal human temperature",
        dataElement: "BH5SRLl5PfH",
        respondedDataElement: "JGnHr6WI3AY",
        displayName: "Sign/Symptoms Present",
    },
    {
        condition: "hasValue(Cs1wQfbUHSV) && length(Cs1wQfbUHSV) != 12",
        action: Action.showError,
        message: "Indicate the format for the south sudan phone format",
        dataElement: "Cs1wQfbUHSV",
        respondedDataElement: "Cs1wQfbUHSV",
        displayName: "Contact phone number while in South Sudan",
    },
    {
        condition:
            "hasValue(Xak52XWejN2) && (Xak52XWejN2 == AOg1wewJiRE || Xak52XWejN2 == KhAl7eY8tdX )",
        action: Action.showError,
        message: "You have already selected this country in 2nd or 1st country you visited",
        dataElement: "Xak52XWejN2",
        respondedDataElement: "Xak52XWejN2",
        displayName: "3rd Country Visited in Last 21 days",
    },
    {
        condition:
            "hasValue(AOg1wewJiRE) && (AOg1wewJiRE == Xak52XWejN2 || AOg1wewJiRE == KhAl7eY8tdX )",
        action: Action.showError,
        message: "You have already selected this country in 3rd or 1st country you visited",
        dataElement: "AOg1wewJiRE",
        respondedDataElement: "AOg1wewJiRE",
        displayName: "2nd Country Visited in Last 21 days",
    },
    {
        condition:
            "hasValue(KhAl7eY8tdX) && (KhAl7eY8tdX == AOg1wewJiRE || KhAl7eY8tdX == Xak52XWejN2 )",
        action: Action.showError,
        message: "You have already selected this country in 3rd or 1st country you visited",
        dataElement: "KhAl7eY8tdX",
        respondedDataElement: "KhAl7eY8tdX",
        displayName: "1st Country Visited in Last 21 days",
    }
] as Dhis2FormElement[];
