export enum METADATA {
  PROGRAM = "ArXGGyMgxL4",
  PROGRAM_STAGE = "ePHVvZFGdZo",
  ATTRIBUTE_CATEGORY_OPTION = "xYerKDKCefk",
  ATTRIBUTE_OPTION_COMBO = "HllvX50cXC0",
  TRIP_INFO_SECTION_ID = "utlt6SfyIs9",
  AIRPORT_ORG_UNIT_GROUP_ID = "",
}

export const PROGRAM = {
  POE_ARRIVAL_HEALTH_POGRAM: "ArXGGyMgxL4",
};
