export enum METADATA {
    PROGRAM = 'ArXGGyMgxL4',
    PROGRAM_STAGE = "ePHVvZFGdZo",
    ATTRIBUTE_CATEGORY_OPTION = "xYerKDKCefk",
    ATTRIBUTE_OPTION_COMBO = "HllvX50cXC0"
}

export const PROGRAM = {
    POE_ARRIVAL_HEALTH_POGRAM: 'ArXGGyMgxL4'
}
